<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE locale [
    <!ELEMENT locale (message*)>
    <!ATTLIST locale lang CDATA #REQUIRED>
    <!ELEMENT message (id, string)>
    <!ATTLIST message module CDATA #REQUIRED>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT string (#PCDATA)>
    <!ENTITY aelig "&amp;aelig;">
    <!ENTITY AElig "&amp;AElig;">
    <!ENTITY aring "&amp;aring;">
    <!ENTITY Aring "&amp;Aring;">
    <!ENTITY oslash "&amp;oslash;">
    <!ENTITY Oslash "&amp;Oslash;">
]>
<locale lang="no">

   <message module="search_person">
      <id>Person Details</id>
      <string>Person Detaljer</string>
   </message>
   <message module="search_person">
      <id>Searched for</id>
      <string>S&oslash;kt
         etter
      </string>
   </message>
   <message module="search_person">
      <id>records found in this DVD Collection</id>
      <string>filmer funnet i denne DVD samlingen</string>
   </message>
   <message module="search_person">
      <id>IMDB Search</id>
      <string>IMDB-S&oslash;k
      </string>
   </message>
   <message module="search_person">
      <id>Wikipedia Search</id>
      <string>Wikipedia
         S&oslash;k
      </string>
   </message>
   <message module="search_person">
      <id>OFDB Search</id>
      <string>OFDB-S&oslash;k
      </string>
   </message>
   <message module="search_person">
      <id>as</id>
      <string>som</string>
   </message>

   <message module="search">
      <id>Search DVD Collection</id>
      <string>S&oslash;k
         i DVD Samlingen
      </string>
   </message>
   <message module="search">
      <id>Find Movie</id>
      <string>Finn Film</string>
   </message>
   <message module="search">
      <id>Search for Movie</id>
      <string>S&oslash;k
         etter Film
      </string>
   </message>
   <message module="search">
      <id>Find Person</id>
      <string>Finn Person</string>
   </message>
   <message module="search">
      <id>Search for Person</id>
      <string>S&oslash;k
         etter Person
      </string>
   </message>
   <message module="search">
      <id>Add Filters</id>
      <string>Legg til Filter</string>
   </message>
   <message module="search">
      <id>Genre</id>
      <string>Sjanger</string>
   </message>
   <message module="search">
      <id>Media Type</id>
      <string>Media Type</string>
   </message>
   <message module="search">
      <id>please select</id>
      <string>vennligst velg</string>
   </message>
   <message module="search">
      <id>Studio</id>
      <string>Studio</string>
   </message>
   <message module="search">
      <id>Media Company</id>
      <string>Media Selskap</string>
   </message>
   <message module="search">
      <id>Tag</id>
      <string>Tag</string>
   </message>
   <message module="search">
      <id>Audio Language</id>
      <string>Tale</string>
   </message>
   <message module="search">
      <id>Region Code</id>
      <string>Sone</string>
   </message>
   <message module="search">
      <id>Remove all filters</id>
      <string>Fjern alle filter</string>
   </message>

   <message module="start">
      <id>Summary</id>
      <string>Oppsummering</string>
   </message>
   <message module="start">
      <id>News</id>
      <string>Nyheter</string>
   </message>
   <message module="start">
      <id>The %c latest DVDs</id>
      <string>De %c Nyeste DVDer</string>
   </message>
   <message module="start">
      <id>Cover</id>
      <string>Omslag</string>
   </message>
   <message module="start">
      <id>Movie Information</id>
      <string>Film Informasjon</string>
   </message>
   <message module="start">
      <id>Purchase Information</id>
      <string>Kj&oslash;ps
         Informasjon
      </string>
   </message>
   <message module="start">
      <id>Year of Production</id>
      <string>Produksjons&aring;r
      </string>
   </message>
   <message module="start">
      <id>Running Time</id>
      <string>Spilletid</string>
   </message>
   <message module="start">
      <id>Minutes</id>
      <string>Minutter</string>
   </message>
   <message module="start">
      <id>Bought</id>
      <string>Kj&oslash;pt
      </string>
   </message>
   <message module="start">
      <id>Ordered </id>
      <string>Bestilt</string>
   </message>
   <message module="start">
      <id>on</id>
      <string>den</string>
   </message>
   <message module="start">
      <id>Release Date</id>
      <string>Utgivelsesdato</string>
   </message>
   <message module="start">
      <id>The %c last ordered DVDs</id>
      <string>De %c siste bestilte DVDer</string>
   </message>
   <message module="start">
      <id>the</id>
      <string>den</string>
   </message>
   <message module="start">
      <id>today</id>
      <string>i dag</string>
   </message>
   <message module="start">
      <id>Built by</id>
      <string>Utviklet av</string>
   </message>
   <message module="start">
      <id>published under General Public License (GPL)</id>
      <string>Utgitt under General Public License (GPL)</string>
   </message>
   <message module="start">
      <id>Last update</id>
      <string>Siste oppdatering</string>
   </message>

   <message module="coverlist">
      <id>Cover Gallery</id>
      <string>Omslagsgalleri</string>
   </message>
   <message module="coverlist">
      <id>Number of covers</id>
      <string>Antall omslag</string>
   </message>

   <message module="top">
      <id>Please activate JavaScript for all functions!</id>
      <string>Vennligst aktiver Javaskript for alle funksjoner</string>
   </message>
   <message module="top">
      <id>Home</id>
      <string>Startside</string>
   </message>
   <message module="top">
      <id>Search</id>
      <string>S&oslash;k
      </string>
   </message>
   <message module="top">
      <id>Administration</id>
      <string>Administrasjon</string>
   </message>
   <message module="top">
      <id>phpMyProfiler Home</id>
      <string>phpMyProfiler Home</string>
   </message>
   <message module="top">
      <id>phpMyProfiler Forum</id>
      <string>phpMyProfiler Forum</string>
   </message>
   <message module="top">
      <id>Credits</id>
      <string>Rulletekst</string>
   </message>

   <message module="credits">
      <id>Credits - phpMyProfiler</id>
      <string>Rulletekst - phpMyProfiler</string>
   </message>
   <message module="credits">
      <id>Name</id>
      <string>Navn</string>
   </message>
   <message module="credits">
      <id>Nick</id>
      <string>Signatur</string>
   </message>
   <message module="credits">
      <id>Developer</id>
      <string>Programmerer</string>
   </message>
   <message module="credits">
      <id>Developer, graphics (till march 2005)</id>
      <string>Grafisk Programmerer (inntil Mars 2005)</string>
   </message>
   <message module="credits">
      <id>Developer of myProfiler (till december 2004)</id>
      <string>Programmerer av myProfiler (inntil Deesember 2004)</string>
   </message>
   <message module="credits">
      <id>Translations</id>
      <string>Oversettelser</string>
   </message>
   <message module="credits">
      <id>Norwegian translation</id>
      <string>Norsk oversettelse</string>
   </message>
   <message module="credits">
      <id>Danish translation</id>
      <string>Dansk oversettelse</string>
   </message>
   <message module="credits">
      <id>Dutch translation</id>
      <string>Nederlandsk oversettelse</string>
   </message>
   <message module="credits">
      <id>Code contributions</id>
      <string>Kode bidrag</string>
   </message>
   <message module="credits">
      <id>Original parser for DVDProfiler 3.X</id>
      <string>Original Parser for DVDProfiler 3.X</string>
   </message>
   <message module="credits">
      <id>Testing, GFX and misc. improvements</id>
      <string>Tester, Grafikk og div forbedringer</string>
   </message>
   <message module="credits">
      <id>Used scripts and libraries in phpMyProfiler</id>
      <string>Benyttede script og biblioteker i phpMyProfiler</string>
   </message>
   <message module="credits">
      <id>Script/library</id>
      <string>Script/Bibliotek</string>
   </message>
   <message module="credits">
      <id>URL</id>
      <string>URL</string>
   </message>
   <message module="credits">
      <id>License</id>
      <string>Lisens</string>
   </message>
   <message module="credits">
      <id>Icons</id>
      <string>Ikoner</string>
   </message>
   <message module="credits">
      <id>All used scripts are liable to the copyright of the corresponding
         author.
      </id>
      <string>Alle benyttede script er underlagt den gjeldende eiers
         copyright.
      </string>
   </message>
   <message module="credits">
      <id>phpMyProfiler is adapted from</id>
      <string>phpMyProfiler
         er baseret p&aring;
      </string>
   </message>
   <message module="credits">
      <id>by</id>
      <string>av</string>
   </message>

   <message module="picturelist">
      <id>Picture Gallery</id>
      <string>Foto Galleri</string>
   </message>
   <message module="picturelist">
      <id>Number of pictures</id>
      <string>Antall bilder</string>
   </message>

   <message module="filmprofile">
      <id>Features</id>
      <string>Presentasjon</string>
   </message>
   <message module="filmprofile">
      <id>This DVD is currently loaned</id>
      <string>Denne
         DVD er i &oslash;yeblikket
         utl&aring;nt
      </string>
   </message>
   <message module="filmprofile">
      <id>Details</id>
      <string>Detaljer</string>
   </message>
   <message module="filmprofile">
      <id>Overview</id>
      <string>Oversikt</string>
   </message>
   <message module="filmprofile">
      <id>Cast &amp; Crew</id>
      <string>Skuespillere &amp; Filmbesetning</string>
   </message>
   <message module="filmprofile">
      <id>Events</id>
      <string>Status</string>
   </message>
   <message module="filmprofile">
      <id>Episode Guide</id>
      <string>Episode Guide</string>
   </message>
   <message module="filmprofile">
      <id>Cover Images</id>
      <string>Omslagsbilder</string>
   </message>
   <message module="filmprofile">
      <id>Boxset Contents</id>
      <string>Boksett Innhold</string>
   </message>
   <message module="filmprofile">
      <id>Part of boxset</id>
      <string>En del av et boks sett</string>
   </message>
   <message module="filmprofile">
      <id>External Links</id>
      <string>Eksterne Linker</string>
   </message>
   <message module="filmprofile">
      <id>International</id>
      <string>Intenasjonal</string>
   </message>

   <message module="filmprofile_page1">
      <id>Country of Origin</id>
      <string>Opphavsland</string>
   </message>
   <message module="filmprofile_page1">
      <id>hrs</id>
      <string>timer</string>
   </message>
   <message module="filmprofile_page1">
      <id>minutes</id>
      <string>minutter</string>
   </message>
   <message module="filmprofile_page1">
      <id>Rating</id>
      <string>Kritikk</string>
   </message>
   <message module="filmprofile_page1">
      <id>Rating Details</id>
      <string>Benytt True Type skrift typer i grafer.</string>
   </message>
   <message module="filmprofile_page1">
      <id>Information</id>
      <string>Informasjon</string>
   </message>
   <message module="filmprofile_page1">
      <id>Edition</id>
      <string>Utgave</string>
   </message>
   <message module="filmprofile_page1">
      <id>ID</id>
      <string>ID</string>
   </message>
   <message module="filmprofile_page1">
      <id>UPC</id>
      <string>EAN</string>
   </message>
   <message module="filmprofile_page1">
      <id>Profile Date</id>
      <string>Profil dato</string>
   </message>
   <message module="filmprofile_page1">
      <id>Last Edited</id>
      <string>Sist redigert</string>
   </message>
   <message module="filmprofile_page1">
      <id>Country</id>
      <string>Land</string>
   </message>
   <message module="filmprofile_page1">
      <id>Regions</id>
      <string>Soner</string>
   </message>
   <message module="filmprofile_page1">
      <id>DVD Release</id>
      <string>DVD Utgivelse</string>
   </message>
   <message module="filmprofile_page1">
      <id>Case Type</id>
      <string>Omslagstype</string>
   </message>
   <message module="filmprofile">
      <id>Media Companies</id>
      <string>Media Selskaper</string>
   </message>
   <message module="filmprofile_page1">
      <id>Slipcover</id>
      <string>Slipcover</string>
   </message>
   <message module="filmprofile_page1">
      <id>State</id>
      <string>Status</string>
   </message>
   <message module="filmprofile_page1">
      <id>Collection Number</id>
      <string>Samlingsnummer</string>
   </message>
   <message module="filmprofile_page1">
      <id>Notes</id>
      <string>Notater</string>
   </message>
   <message module="filmprofile_page1">
      <id>Purchased</id>
      <string>Kj&oslash;pt
      </string>
   </message>
   <message module="filmprofile_page1">
      <id>at</id>
      <string>hos</string>
   </message>
   <message module="filmprofile_page1">
      <id>for</id>
      <string>for</string>
   </message>
   <message module="filmprofile_page1">
      <id>SRP</id>
      <string>UVP</string>
   </message>
   <message module="filmprofile_page1">
      <id>Rented by</id>
      <string>Utl&aring;nt
         til
      </string>
   </message>
   <message module="filmprofile_page1">
      <id>Return Date</id>
      <string>Retur Dato</string>
   </message>
   <message module="filmprofile_page1">
      <id>Tags</id>
      <string>Tags</string>
   </message>
   <message module="filmprofile_page1">
      <id>Review</id>
      <string>Anmeldelse</string>
   </message>
   <message module="filmprofile_page1">
      <id>Movie</id>
      <string>Film</string>
   </message>
   <message module="filmprofile_page1">
      <id>DVD</id>
      <string>DVD</string>
   </message>
   <message module="filmprofile_page1">
      <id>Audio</id>
      <string>Lydformat</string>
   </message>
   <message module="filmprofile_page1">
      <id>Extras</id>
      <string>Ekstra materiale</string>
   </message>
   <message module="filmprofile_page1">
      <id>votes</id>
      <string>stemmer</string>
   </message>
   <message module="filmprofile_page1">
      <id>Extern Reviews</id>
      <string>Eksterne anmeldelser</string>
   </message>
   <message module="filmprofile_page1">
      <id>IMDB User Rating</id>
      <string>IMDB Bruker Karakter</string>
   </message>
   <message module="filmprofile_page1">
      <id>IMDB Top 250</id>
      <string>IMDB Top 250</string>
   </message>
   <message module="filmprofile_page1">
      <id>IMDB Bottom 100</id>
      <string>IMDB Siste 100</string>
   </message>
   <message module="filmprofile_page1">
      <id>User Reviews</id>
      <string>Bruker anmeldelser</string>
   </message>
   <message module="filmprofile_page1">
      <id>Compose a review</id>
      <string>Skriv en anmeldelse</string>
   </message>

   <message module="filmprofile_page2">
      <id>Format</id>
      <string>Format</string>
   </message>
   <message module="filmprofile_page2">
      <id>Compression</id>
      <string>Komprimering</string>
   </message>
   <message module="filmprofile_page2">
      <id>Content</id>
      <string>Spr&aring;k
      </string>
   </message>
   <message module="filmprofile_page2">
      <id>Subtitles</id>
      <string>Tekst</string>
   </message>
   <message module="filmprofile_page2">
      <id>Video Information</id>
      <string>Video Informmasjon</string>
   </message>
   <message module="filmprofile_page2">
      <id>Video Format</id>
      <string>Video Format</string>
   </message>
   <message module="filmprofile_page2">
      <id>Aspect Ratio</id>
      <string>Bilde Format</string>
   </message>
   <message module="filmprofile_page2">
      <id>THX Certified</id>
      <string>THX Sertifisert</string>
   </message>
   <message module="filmprofile_page2">
      <id>Scene Access</id>
      <string>Scene Tilgang</string>
   </message>
   <message module="filmprofile_page2">
      <id>Commentary</id>
      <string>Kommentar</string>
   </message>
   <message module="filmprofile_page2">
      <id>Trailers</id>
      <string>Trailere</string>
   </message>
   <message module="filmprofile_page2">
      <id>Deleted Scenes</id>
      <string>Slettede Scener</string>
   </message>
   <message module="filmprofile_page2">
      <id>Featurettes</id>
      <string>Featurettes</string>
   </message>
   <message module="filmprofile_page2">
      <id>Interviews</id>
      <string>Intervjuer</string>
   </message>
   <message module="filmprofile_page2">
      <id>Storyboard Comparisons</id>
      <string>Storyboard Comparisons</string>
   </message>
   <message module="filmprofile_page2">
      <id>DVD-ROM Content</id>
      <string>DVD-ROM Innhold</string>
   </message>
   <message module="filmprofile_page2">
      <id>Interactive Games</id>
      <string>Interaktive Spill</string>
   </message>
   <message module="filmprofile_page2">
      <id>Multi-angle</id>
      <string>Multi-Vinkel</string>
   </message>
   <message module="filmprofile_page2">
      <id>Music Videos</id>
      <string>Musikkvideoer</string>
   </message>
   <message module="filmprofile_page2">
      <id>Prod. Notes</id>
      <string>Prod. Notater</string>
   </message>
   <message module="filmprofile_page2">
      <id>Photo Gallery</id>
      <string>Bilde Galleri</string>
   </message>
   <message module="filmprofile_page2">
      <id>Outtakes/Bloopers</id>
      <string>Slettede Scener/Snutter</string>
   </message>
   <message module="filmprofile_page2">
      <id>Closed Captioned</id>
      <string>Closed Captioned</string>
   </message>
   <message module="filmprofile_page2">
      <id>Bonus Trailers</id>
      <string>Bonus Trailere</string>
   </message>
   <message module="filmprofile_page2">
      <id>Picture-in-Picture</id>
      <string>Bilde i bilde</string>
   </message>
   <message module="filmprofile_page2">
      <id>BD-Live</id>
      <string>BD-Live</string>
   </message>
   <message module="filmprofile_page2">
      <id>Digital Copy</id>
      <string>Digital kopi</string>
   </message>
   <message module="filmprofile_page2">
      <id>Other Features</id>
      <string>Annet Innhold</string>
   </message>
   <message module="filmprofile_page2">
      <id>Additional Information</id>
      <string>Utvidet Informasjon</string>
   </message>
   <message module="filmprofile_page2">
      <id>Studios</id>
      <string>Studio</string>
   </message>
   <message module="filmprofile_page2">
      <id>Genres</id>
      <string>Genre</string>
   </message>
   <message module="filmprofile_page2">
      <id>Media Info</id>
      <string>Disc Info</string>
   </message>
   <message module="filmprofile_page2">
      <id>Description Side A</id>
      <string>Beskrivelse Side A</string>
   </message>
   <message module="filmprofile_page2">
      <id>Label Side A</id>
      <string>Etikett Side A</string>
   </message>
   <message module="filmprofile_page2">
      <id>Duallayer Side A</id>
      <string>Tolags Side A</string>
   </message>
   <message module="filmprofile_page2">
      <id>DiscID Side A</id>
      <string>Disk-ID Side A</string>
   </message>
   <message module="filmprofile_page2">
      <id>Description Side B</id>
      <string>Beskrivelse Side B</string>
   </message>
   <message module="filmprofile_page2">
      <id>Label Side B</id>
      <string>Etikett Side B</string>
   </message>
   <message module="filmprofile_page2">
      <id>DiscID Side B</id>
      <string>Disk-ID Side B</string>
   </message>
   <message module="filmprofile_page2">
      <id>Duallayer Side B</id>
      <string>Tolags Side B</string>
   </message>
   <message module="filmprofile_page2">
      <id>Dualsided</id>
      <string>Tosidet</string>
   </message>
   <message module="filmprofile_page2">
      <id>Dual Layered</id>
      <string>Tolags</string>
   </message>
   <message module="filmprofile_page2">
      <id>Single Layered</id>
      <string>Et lags</string>
   </message>
   <message module="filmprofile_page2">
      <id>Location</id>
      <string>Sted</string>
   </message>
   <message module="filmprofile_page2">
      <id>Slot</id>
      <string>Slot</string>
   </message>
   <message module="filmprofile_page2">
      <id>Various Information</id>
      <string>Diverse Informasjon</string>
   </message>
   <message module="filmprofile_page2">
      <id>Easter Egg</id>
      <string>P&aring;ske
         Egg
      </string>
   </message>
   <message module="filmprofile_page2">
      <id>Awards</id>
      <string>Film Priser</string>
   </message>
   <message module="filmprofile_page2">
      <id>Winner</id>
      <string>Vinnere</string>
   </message>
   <message module="filmprofile_page2">
      <id>Nominee for</id>
      <string>Nominert for</string>
   </message>

   <message module="filmprofile_page3">
      <id>Cast</id>
      <string>Medvirkere</string>
   </message>
   <message module="filmprofile_page3">
      <id>uncredited</id>
      <string>Ikke krediterte</string>
   </message>
   <message module="filmprofile_page3">
      <id>voice</id>
      <string>stemme</string>
   </message>
   <message module="filmprofile_page3">
      <id>credited as</id>
      <string>kreditert som</string>
   </message>
   <message module="filmprofile_page3">
      <id>Crew</id>
      <string>Filmbesetning</string>
   </message>

   <message module="filmprofile_page4">
      <id>Date</id>
      <string>Dato</string>
   </message>
   <message module="filmprofile_page4">
      <id>Event</id>
      <string>Hendelse</string>
   </message>
   <message module="filmprofile_page4">
      <id>Phone</id>
      <string>Telefon</string>
   </message>
   <message module="filmprofile_page4">
      <id>Borrowed</id>
      <string>Utl&aring;nt
      </string>
   </message>
   <message module="filmprofile_page4">
      <id>Returned</id>
      <string>Returnert</string>
   </message>

   <message module="filmprofile_status">
      <id>Owned</id>
      <string>Egne DVDer</string>
   </message>
   <message module="filmprofile_status">
      <id>Ordered</id>
      <string>Bestilte DVDer</string>
   </message>
   <message module="filmprofile_status">
      <id>WishList</id>
      <string>&Oslash;nskeliste
      </string>
   </message>

   <message module="filmprofile_wishpriority">
      <id>Vague Interest</id>
      <string>Vag Interesse</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Like to Have It</id>
      <string>Vil gjerne eie</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Want It</id>
      <string>Vil eie den</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Really Want</id>
      <string>Vil veldig gjerne eie</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Need It</id>
      <string>Skal ha</string>
   </message>
   <message module="filmprofile_wishpriority">
      <id>Watched</id>
      <string>Sett</string>
   </message>

   <message module="statistics">
      <id>Statistics</id>
      <string>Statistikk</string>
   </message>
   <message module="statistics">
      <id>Other Statistics</id>
      <string>Annen Statistikk</string>
   </message>
   <message module="statistics">
      <id>Director Statistic</id>
      <string>Regiss&oslash;r
         Statistikk
      </string>
   </message>
   <message module="statistics">
      <id>Producer Statistic</id>
      <string>Produsent Statistikk</string>
   </message>
   <message module="statistics">
      <id>Writer &amp; Screenwriter Statistic</id>
      <string>Forfatter &amp; Manusforfatter Statistikk</string>
   </message>
   <message module="statistics">
      <id>Composer Statistic</id>
      <string>Komponist Statistikk</string>
   </message>
   <message module="statistics">
      <id>Actor Statistic</id>
      <string>Skuespiller Statistikk</string>
   </message>
   <message module="statistics">
      <id> s</id>
      <string>Antall DVDer</string>
   </message>
   <message module="statistics">
      <id>With Pricing Information</id>
      <string>DVDer med Pris Informasjon</string>
   </message>
   <message module="statistics">
      <id>DVDs without a Child Profile</id>
      <string>DVDer uten Barne Profil</string>
   </message>
   <message module="statistics">
      <id>Boxset Profiles</id>
      <string>Samleboks Profiler</string>
   </message>
   <message module="statistics">
      <id>Child Profiles</id>
      <string>Barne Profiler</string>
   </message>
   <message module="statistics">
      <id>DVDs with Collection Number</id>
      <string>DVDer med Samlingsnummer</string>
   </message>
   <message module="statistics">
      <id>DVDs with Rating Information</id>
      <string>DVDer med Kritikk Vurdering</string>
   </message>
   <message module="statistics">
      <id>Price of all DVDs</id>
      <string>Samlet pris for alle DVDer</string>
   </message>
   <message module="statistics">
      <id>Average price</id>
      <string>Gjennomsnitts pris</string>
   </message>
   <message module="statistics">
      <id>Most expensive DVDs</id>
      <string>De dyreste DVDer</string>
   </message>
   <message module="statistics">
      <id>Cheapest DVDs</id>
      <string>De billigste DVDer</string>
   </message>
   <message module="statistics">
      <id>Length of all DVDs</id>
      <string>Samlet spilletid for alle DVDer</string>
   </message>
   <message module="statistics">
      <id>DVDs with Length Information</id>
      <string>DVDer med spilletids informasjon</string>
   </message>
   <message module="statistics">
      <id>Hours: about</id>
      <string>Timer: ca.</string>
   </message>
   <message module="statistics">
      <id>hours</id>
      <string>Timer</string>
   </message>
   <message module="statistics">
      <id>Days: about</id>
      <string>Dager: ca.</string>
   </message>
   <message module="statistics">
      <id>days</id>
      <string>dager</string>
   </message>
   <message module="statistics">
      <id>Weeks: about</id>
      <string>Uker: ca.</string>
   </message>
   <message module="statistics">
      <id>weeks</id>
      <string>uker</string>
   </message>
   <message module="statistics">
      <id>Months: about</id>
      <string>M&aring;neder:
         ca.
      </string>
   </message>
   <message module="statistics">
      <id>months</id>
      <string>m&aring;neder
      </string>
   </message>
   <message module="statistics">
      <id>Years: about</id>
      <string>&Aring;r:
         ca.
      </string>
   </message>
   <message module="statistics">
      <id>years</id>
      <string>&aring;r
      </string>
   </message>
   <message module="statistik">
      <id>Average Length</id>
      <string>Gjennomsnittslengde</string>
   </message>
   <message module="statistics">
      <id>Longest DVDs</id>
      <string>De lengste DVDene</string>
   </message>
   <message module="statistics">
      <id>Shortest DVDs</id>
      <string>De korteste DVDene</string>
   </message>
   <message module="statistics">
      <id>Regioncode</id>
      <string>Sone</string>
   </message>
   <message module="statistics">
      <id>Localities of DVDs</id>
      <string>Utgivelsesland</string>
   </message>
   <message module="statistics">
      <id>Localities</id>
      <string>Utgivelsesland</string>
   </message>
   <message module="statistics">
      <id>Origins of Movies</id>
      <string>Produksjonsland</string>
   </message>
   <message module="statistics">
      <id>Origins</id>
      <string>Produksjonsland</string>
   </message>
   <message module="statistics">
      <id>Ratings</id>
      <string>Aldersgrense</string>
   </message>
   <message module="statistics">
      <id>DVDs</id>
      <string>DVDer</string>
   </message>
   <message module="statistics">
      <id>Year of Purchase</id>
      <string>Kj&oslash;ps&aring;r
      </string>
   </message>
   <message module="statistics">
      <id>Detailed Statistic</id>
      <string>Detaljert Statistikk</string>
   </message>
   <message module="statistics">
      <id>total price</id>
      <string>samlet pris</string>
   </message>
   <message module="statistics">
      <id>Production Decade</id>
      <string>Produksjons
         ti&aring;r
      </string>
   </message>
   <message module="statistics">
      <id>Place of Purchase (Top 10)</id>
      <string>Kj&oslash;pssted
         (Topp 10)
      </string>
   </message>
   <message module="statistics">
      <id>Place of Purchase</id>
      <string>Kj&oslash;pssted
      </string>
   </message>
   <message module="statistics">
      <id>Genre (Top 10)</id>
      <string>Genre (Topp 10)</string>
   </message>
   <message module="statistics">
      <id>Studio (Top 10)</id>
      <string>Studio (Topp 10)</string>
   </message>
   <message module="statistics">
      <id>Media Companies (Top 10)</id>
      <string>Media Selskaper (Topp 10)</string>
   </message>
   <message module="statistics">
      <id>Visitors</id>
      <string>Bes&oslash;kende
      </string>
   </message>
   <message module="statistics">
      <id>Visited DVDs</id>
      <string>Bes&oslash;kte
         DVDer
      </string>
   </message>

   <message module="statistics_graph">
      <id>owned</id>
      <string>Egne</string>
   </message>
   <message module="statistics_graph">
      <id>ordered</id>
      <string>bestilt</string>
   </message>
   <message module="statistics_graph">
      <id>wishlist</id>
      <string>&oslash;nskeliste
      </string>
   </message>

   <message module="statisticsdetail">
      <id>Visitor Statistic</id>
      <string>Bes&oslash;ks
         Statistikk
      </string>
   </message>
   <message module="statisticsdetail">
      <id>Profile Statistic</id>
      <string>Profil Statistikk</string>
   </message>