<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE locale [
    <!ELEMENT locale (message*)>
    <!ATTLIST locale
    	lang CDATA #REQUIRED
    >
    <!ELEMENT message (id, string)>
    <!ATTLIST message
    	module CDATA #REQUIRED
    >
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT string (#PCDATA)>
    <!ENTITY auml "&amp;auml;">
    <!ENTITY ouml "&amp;ouml;">
    <!ENTITY uuml "&amp;uuml;">
    <!ENTITY Auml "&amp;Auml;">
    <!ENTITY Ouml "&amp;Ouml;">
    <!ENTITY Uuml "&amp;Uuml;">
    <!ENTITY szlig "&amp;szlig;">
    <!ENTITY Oslash "&amp;Oslash;">
]>
<locale lang="de">

  <message module="search_person">
    <id>Person Details</id>
    <string>Personen Details</string>
  </message>
  <message module="search_person">
    <id>Searched for</id>
    <string>Suche nach</string>
  </message>
  <message module="search_person">
    <id>records found in this DVD Collection</id>
    <string>Ergebnis(se) in dieser DVD Sammlung gefunden</string>
  </message>
  <message module="search_person">
    <id>IMDB Search</id>
    <string>IMDB-Suche</string>
  </message>
  <message module="search_person">
    <id>Wikipedia Search</id>
    <string>Wikipedia-Suche</string>
  </message>
  <message module="search_person">
    <id>OFDB Search</id>
    <string>OFDB-Suche</string>
  </message>
  <message module="search_person">
    <id>as</id>
    <string>als</string>
  </message>
  <message module="search_person">
    <id>in</id>
    <string>in</string>
  </message>
  <message module="search_person">
    <id>episodes</id>
    <string>Episoden</string>
  </message>


  <message module="search">
    <id>Search DVD Collection</id>
    <string>Durchsuche DVD Sammlung</string>
  </message>
  <message module="search">
    <id>Find Movie</id>
    <string>Filmsuche</string>
  </message>
  <message module="search">
    <id>Search for Movie</id>
    <string>Suche nach Film</string>
  </message>
  <message module="search">
    <id>Find Person</id>
    <string>Personensuche</string>
  </message>
  <message module="search">
    <id>Search for Person</id>
    <string>Suche nach Person</string>
  </message>
  <message module="search">
    <id>Add Filters</id>
    <string>Filter hinzuf&uuml;gen</string>
  </message>
  <message module="search">
    <id>Genre</id>
    <string>Genre</string>
  </message>
  <message module="search">
    <id>Media Type</id>
    <string>Medien Typ</string>
  </message>
  <message module="search">
    <id>please select</id>
    <string>Bitte w&auml;hlen</string>
  </message>
  <message module="search">
    <id>Studio</id>
    <string>Studio</string>
  </message>
  <message module="search">
    <id>Media Company</id>
    <string>Vertrieb</string>
  </message>
  <message module="search">
    <id>Tag</id>
    <string>Tag</string>
  </message>
  <message module="search">
    <id>Audio Language</id>
    <string>Audiosprache</string>
  </message>
  <message module="search">
    <id>Region Code</id>
    <string>Regionalcode</string>
  </message>
  <message module="search">
    <id>Remove all filters</id>
    <string>Alle Filter entfernen</string>
  </message>

  <message module="start">
    <id>Summary</id>
    <string>&Uuml;bersicht</string>
  </message>
  <message module="start">
    <id>News</id>
    <string>Neuigkeiten</string>
  </message>
  <message module="start">
    <id>The %c latest DVDs</id>
    <string>Die letzten %c Neuzug&auml;nge</string>
  </message>
  <message module="start">
    <id>Cover</id>
    <string>Cover</string>
  </message>
  <message module="start">
    <id>Movie Information</id>
    <string>Filminformationen</string>
  </message>
  <message module="start">
    <id>Purchase Information</id>
    <string>Kaufinformationen</string>
  </message>
  <message module="start">
    <id>Year of Production</id>
    <string>Produktionsjahr</string>
  </message>
  <message module="start">
    <id>Running Time</id>
    <string>Laufzeit</string>
  </message>
  <message module="start">
    <id>Minutes</id>
    <string>Minuten</string>
  </message>
  <message module="start">
    <id>Bought</id>
    <string>Gekauft</string>
  </message>
  <message module="start">
    <id>Ordered </id>
    <string>Bestellt </string>
  </message>
  <message module="start">
    <id>on</id>
    <string>am</string>
  </message>
  <message module="start">
    <id>Release Date</id>
    <string>Ver&ouml;ffentlichung</string>
  </message>
  <message module="start">
    <id>The %c last ordered DVDs</id>
    <string>Die letzten %c bestellten DVDs</string>
  </message>
  <message module="start">
    <id>the</id>
    <string>am</string>
  </message>
  <message module="start">
    <id>today</id>
    <string>heute</string>
  </message>
  <message module="start">
    <id>Built by</id>
    <string>Erstellt von</string>
  </message>
  <message module="start">
    <id>published under General Public License (GPL)</id>
    <string>ver&ouml;ffentlicht unter General Public License (GPL)</string>
  </message>
  <message module="start">
    <id>Last update</id>
    <string>Letzte Aktualisierung</string>
  </message>

  <message module="coverlist">
    <id>Cover Gallery</id>
    <string>Covergallerie</string>
  </message>
  <message module="coverlist">
    <id>Number of covers</id>
    <string>Anzahl Cover</string>
  </message>

  <message module="top">
    <id>Please activate JavaScript for all functions!</id>
    <string>Bitte aktivieren Sie JavaScript f&uuml;r alle Funktionen!</string>
  </message>
  <message module="top">
    <id>Home</id>
    <string>Startseite</string>
  </message>
  <message module="top">
    <id>Search</id>
    <string>Suche</string>
  </message>
  <message module="top">
    <id>Administration</id>
    <string>Adminstration</string>
  </message>
  <message module="top">
    <id>phpMyProfiler Home</id>
    <string>phpMyProfiler Home</string>
  </message>
  <message module="top">
    <id>phpMyProfiler Forum</id>
    <string>phpMyProfiler Forum</string>
  </message>
  <message module="top">
    <id>Credits</id>
    <string>Credits</string>
  </message>

  <message module="credits">
    <id>Credits - phpMyProfiler</id>
    <string>Credits - phpMyProfiler</string>
  </message>
  <message module="credits">
    <id>Name</id>
    <string>Name</string>
  </message>
  <message module="credits">
    <id>Nick</id>
    <string>Nick</string>
  </message>
  <message module="credits">
    <id>Developer</id>
    <string>Programmierer</string>
  </message>
  <message module="credits">
    <id>Developer, graphics (till march 2005)</id>
    <string>Programmierer, Grafiker (bis M&auml;rz 05)</string>
  </message>
  <message module="credits">
    <id>Developer of myProfiler (till december 2004)</id>
    <string>Programmierer myProfiler (bis Dezember 04)</string>
  </message>
  <message module="credits">
    <id>Translations</id>
    <string>&Uuml;bersetzungen</string>
  </message>
  <message module="credits">
    <id>Norwegian translation</id>
    <string>Norwegische &Uuml;bersetzung</string>
  </message>
  <message module="credits">
    <id>Danish translation</id>
    <string>D&auml;nische &Uuml;bersetzung</string>
  </message>
  <message module="credits">
    <id>Dutch translation</id>
    <string>Niederl&auml;ndische &Uuml;bersetzung</string>
  </message>
  <message module="credits">
    <id>Code contributions</id>
    <string>Codebeitr&auml;ge</string>
  </message>
  <message module="credits">
    <id>Original parser for DVDProfiler 3.X</id>
    <string>Originaler Parser f&uuml;r DVDProfiler 3.X</string>
  </message>
  <message module="credits">
    <id>Testing, GFX and misc. improvements</id>
    <string>Tester, Grafiken und verschiedene Verbesserungen</string>
  </message>
  <message module="credits">
    <id>Used scripts and libraries in phpMyProfiler</id>
    <string>In phpMyProfiler verwendete Skripte und Bibliotheken</string>
  </message>
  <message module="credits">
    <id>Script/library</id>
    <string>Skript/Bibliothek</string>
  </message>
  <message module="credits">
    <id>URL</id>
    <string>URL</string>
  </message>
  <message module="credits">
    <id>License</id>
    <string>Lizenz</string>
  </message>
  <message module="credits">
    <id>Icons</id>
    <string>Icons</string>
  </message>
  <message module="credits">
    <id>All used scripts are liable to the copyright of the corresponding author.</id>
    <string>Alle verwendeten Skripte unterliegen dem Copyright des jeweilgen Autors.</string>
  </message>
  <message module="credits">
    <id>phpMyProfiler is adapted from</id>
    <string>phpMyProfiler basiert auf</string>
  </message>
  <message module="credits">
    <id>by</id>
    <string>von</string>
  </message>

  <message module="picturelist">
    <id>Picture Gallery</id>
    <string>Bildergallerie</string>
  </message>
  <message module="picturelist">
    <id>Number of pictures</id>
    <string>Anzahl Bilder</string>
  </message>

  <message module="filmprofile">
    <id>Features</id>
    <string>Eigenschaften</string>
  </message>
  <message module="filmprofile">
    <id>This DVD is currently loaned</id>
    <string>Diese DVD ist zur Zeit verliehen</string>
  </message>
  <message module="filmprofile">
    <id>Details</id>
    <string>Details</string>
  </message>
  <message module="filmprofile">
    <id>Overview</id>
    <string>&Uuml;berblick</string>
  </message>
  <message module="filmprofile">
    <id>Cast &amp; Crew</id>
    <string>Cast &amp; Crew</string>
  </message>
  <message module="filmprofile">
    <id>Events</id>
    <string>Ereignisse</string>
  </message>
  <message module="filmprofile">
    <id>Episode Guide</id>
    <string>Episodenguide</string>
  </message>
  <message module="filmprofile">
    <id>Cover Images</id>
    <string>Coverbilder</string>
  </message>
  <message module="filmprofile">
    <id>Boxset Contents</id>
    <string>Boxsetinhalt</string>
  </message>
  <message module="filmprofile">
    <id>Part of boxset</id>
    <string>Teil von Boxset</string>
  </message>
  <message module="filmprofile">
    <id>External Links</id>
    <string>Externe Links</string>
  </message>
  <message module="filmprofile">
    <id>International</id>
    <string>International</string>
  </message>
  <message module="filmprofile">
    <id>My Links</id>
    <string>Meine Links</string>
  </message>
  <message module="filmprofile">
    <id>Official Websites</id>
    <string>Offizielle Webseiten</string>
  </message>
  <message module="filmprofile">
    <id>Fan Sites</id>
    <string>Fan-Seiten</string>
  </message>
  <message module="filmprofile">
    <id>Trailers and Clips</id>
    <string>Trailer und Clips</string>
  </message>
  <message module="filmprofile">
    <id>Reviews</id>
    <string>Bewertungen</string>
  </message>
  <message module="filmprofile">
    <id>Ratings</id>
    <string>Freigaben</string>
  </message>
  <message module="filmprofile">
    <id>General Information</id>
    <string>Allgemeine Informationen</string>
  </message>
  <message module="filmprofile">
    <id>Games</id>
    <string>Spiele</string>
  </message>
  <message module="filmprofile">
    <id>Other</id>
    <string>Sonstiges</string>
  </message>
  <message module="filmprofile">
    <id>Hidden</id>
    <string>Versteckt</string>
  </message>

  <message module="filmprofile_page1">
    <id>Country of Origin</id>
    <string>Produktionsland</string>
  </message>
  <message module="filmprofile_page1">
    <id>hrs</id>
    <string>Stunden</string>
  </message>
  <message module="filmprofile_page1">
    <id>minutes</id>
    <string>Minuten</string>
  </message>
  <message module="filmprofile_page1">
    <id>Rating</id>
    <string>Altersfreigabe</string>
  </message>
  <message module="filmprfilmprofile_page1ofile">
    <id>Rating Details</id>
    <string>Freigabe-Details</string>
  </message>
  <message module="filmprofile_page1">
    <id>Information</id>
    <string>Information</string>
  </message>
  <message module="filmprofile_page1">
    <id>Edition</id>
    <string>Edition</string>
  </message>
  <message module="filmprofile_page1">
    <id>ID</id>
    <string>ID</string>
  </message>
  <message module="filmprofile_page1">
    <id>UPC</id>
    <string>EAN</string>
  </message>
  <message module="filmprofile_page1">
    <id>Profile Date</id>
    <string>Profildatum</string>
  </message>
  <message module="filmprofile_page1">
    <id>Last Edited</id>
    <string>Letzte &Auml;nderung</string>
  </message>
  <message module="filmprofile_page1">
    <id>Country</id>
    <string>Land</string>
  </message>
  <message module="filmprofile_page1">
    <id>Regions</id>
    <string>Regionalcodes</string>
  </message>
  <message module="filmprofile_page1">
    <id>Release</id>
    <string>Ver&ouml;ffentlichung</string>
  </message>
  <message module="filmprofile_page1">
    <id>Case Type</id>
    <string>Verpackung</string>
  </message>
  <message module="filmprofile_page1">
    <id>Media Companies</id>
    <string>Vertrieb</string>
  </message>
  <message module="filmprofile_page1">
    <id>Slipcover</id>
    <string>Schutzh&uuml;lle</string>
  </message>
  <message module="filmprofile_page1">
    <id>State</id>
    <string>Sammlungsstatus</string>
  </message>
  <message module="filmprofile_page1">
    <id>Collection Number</id>
    <string>Sammlungsnummer</string>
  </message>
  <message module="filmprofile_page1">
    <id>Notes</id>
    <string>Notizen</string>
  </message>
  <message module="filmprofile_page1">
    <id>Purchased</id>
    <string>Gekauft am</string>
  </message>
  <message module="filmprofile_page1">
    <id>Gift from</id>
    <string>Geschenkt von</string>
  </message>
  <message module="filmprofile_page1">
    <id>at</id>
    <string>bei</string>
  </message>
  <message module="filmprofile_page1">
    <id>for</id>
    <string>f&uuml;r</string>
  </message>
  <message module="filmprofile_page1">
    <id>SRP</id>
    <string>UVP</string>
  </message>
  <message module="filmprofile_page1">
    <id>Rented by</id>
    <string>Ausgeliehen an</string>
  </message>
  <message module="filmprofile_page1">
    <id>Return Date</id>
    <string>R&uuml;ckgabedatum</string>
  </message>
  <message module="filmprofile_page1">
    <id>Tags</id>
    <string>Tags</string>
  </message>
  <message module="filmprofile_page1">
    <id>Review</id>
    <string>Kurzkritik</string>
  </message>
  <message module="filmprofile_page1">
    <id>Movie</id>
    <string>Film</string>
  </message>
  <message module="filmprofile_page1">
    <id>DVD</id>
    <string>DVD</string>
  </message>
  <message module="filmprofile_page1">
    <id>Audio</id>
    <string>Tonformat</string>
  </message>
  <message module="filmprofile_page1">
    <id>Extras</id>
    <string>Extras</string>
  </message>
  <message module="filmprofile_page1">
    <id>votes</id>
    <string>Stimmen</string>
  </message>
  <message module="filmprofile_page1">
    <id>External Reviews</id>
    <string>Externe Kritiken</string>
  </message>
  <message module="filmprofile_page1">
    <id>IMDB User Rating</id>
    <string>IMDB Benutzer-Bewertung</string>
  </message>
  <message module="filmprofile_page1">
    <id>IMDB Top 250</id>
    <string>IMDB Top 250</string>
  </message>
  <message module="filmprofile_page1">
    <id>IMDB Bottom 100</id>
    <string>IMDB Bottom 100</string>
  </message>
  <message module="filmprofile_page1">
    <id>OFDB User Rating</id>
    <string>OFDB Benutzer-Bewertung</string>
  </message>
  <message module="filmprofile_page1">
    <id>OFDB Top 250</id>
    <string>OFDB Top 250</string>
  </message>
  <message module="filmprofile_page1">
    <id>OFDB Bottom 100</id>
    <string>OFDB Bottom 100</string>
  </message>
  <message module="filmprofile_page1">
    <id>RottenTomatoes Critics Rating</id>
    <string>RottenTomatoes Kritiker-Bewertung</string>
  </message>
  <message module="filmprofile_page1">
    <id>RottenTomatoes User Rating</id>
    <string>RottenTomatoes Benutzer-Bewertung</string>
  </message>
  <message module="filmprofile_page1">
    <id>User Reviews</id>
    <string>Benutzerkritiken</string>
  </message>
  <message module="filmprofile_page1">
    <id>Compose a review</id>
    <string>Verfasse eine Kurzkritik</string>
  </message>

  <message module="filmprofile_page2">
    <id>Format</id>
    <string>Format</string>
  </message>
  <message module="filmprofile_page2">
    <id>Channels</id>
    <string>Kan&auml;le</string>
  </message>
  <message module="filmprofile_page2">
    <id>Content</id>
    <string>Inhalt</string>
  </message>
  <message module="filmprofile_page2">
    <id>Subtitles</id>
    <string>Untertitel</string>
  </message>
  <message module="filmprofile_page2">
    <id>Video Information</id>
    <string>Videoinformationen</string>
  </message>
  <message module="filmprofile_page2">
    <id>Video Format</id>
    <string>Videostandard</string>
  </message>
  <message module="filmprofile_page2">
    <id>Aspect Ratio</id>
    <string>Seitenverh&auml;ltnis</string>
  </message>
  <message module="filmprofile_page2">
    <id>Color</id>
    <string>Farbe</string>
  </message>
  <message module="filmprofile_page2">
    <id>Black & White</id>
    <string>Schwarz-wei&szlig;</string>
  </message>
  <message module="filmprofile_page2">
    <id>Colorized</id>
    <string>Coloriert</string>
  </message>
  <message module="filmprofile_page2">
    <id>Multiple</id>
    <string>Mehrere</string>
  </message>
  <message module="filmprofile_page2">
    <id>Mixed</id>
    <string>Gemischt</string>
  </message>
  <message module="filmprofile_page2">
    <id>Dimensions</id>
    <string>Dimensionen</string>
  </message>
  <message module="filmprofile_page2">
    <id>THX Certified</id>
    <string>THX zertifiziert</string>
  </message>
  <message module="filmprofile_page2">
    <id>Scene Access</id>
    <string>Szenenanwahl</string>
  </message>
  <message module="filmprofile_page2">
    <id>Commentary</id>
    <string>Kommentar</string>
  </message>
  <message module="filmprofile_page2">
    <id>Feature Trailers</id>
    <string>Hauptfilm-Trailer</string>
  </message>
  <message module="filmprofile_page2">
    <id>Deleted Scenes</id>
    <string>Gel&ouml;schte Szenen</string>
  </message>
  <message module="filmprofile_page2">
    <id>Featurettes</id>
    <string>Featurettes</string>
  </message>
  <message module="filmprofile_page2">
    <id>Interviews</id>
    <string>Interviews</string>
  </message>
  <message module="filmprofile_page2">
    <id>Storyboard Comparisons</id>
    <string>Storyboardvergleiche</string>
  </message>
  <message module="filmprofile_page2">
    <id>DVD-ROM Content</id>
    <string>DVD-ROM Inhalt</string>
  </message>
  <message module="filmprofile_page2">
    <id>Interactive Games</id>
    <string>Interaktive Spiele</string>
  </message>
  <message module="filmprofile_page2">
    <id>Multi-angle</id>
    <string>Multi-Angle</string>
  </message>
  <message module="filmprofile_page2">
    <id>Music Videos</id>
    <string>Musikvideos</string>
  </message>
  <message module="filmprofile_page2">
    <id>Prod. Notes</id>
    <string>Prod. Notizen</string>
  </message>
  <message module="filmprofile_page2">
    <id>Photo Gallery</id>
    <string>Photogalerie</string>
  </message>
  <message module="filmprofile_page2">
    <id>Outtakes/Bloopers</id>
    <string>Outtakes/Bloopers</string>
  </message>
  <message module="filmprofile_page2">
    <id>Closed Captioned</id>
    <string>Closed Captioned</string>
  </message>
  <message module="filmprofile_page2">
    <id>Bonus Trailers</id>
    <string>Bonus-Trailer</string>
  </message>
  <message module="filmprofile_page2">
    <id>Picture-in-Picture</id>
    <string>Bild-in-Bild</string>
  </message>
  <message module="filmprofile_page2">
    <id>BD-Live</id>
    <string>BD-Live</string>
  </message>
  <message module="filmprofile_page2">
    <id>Digital Copy</id>
    <string>Digitale-Kopie</string>
  </message>
  <message module="filmprofile_page2">
    <id>Other Features</id>
    <string>Weitere Features</string>
  </message>
  <message module="filmprofile_page2">
    <id>Additional Information</id>
    <string>Zus&auml;tzliche Informationen</string>
  </message>
  <message module="filmprofile_page2">
    <id>Studios</id>
    <string>Studios</string>
  </message>
  <message module="filmprofile_page2">
    <id>Genres</id>
    <string>Genres</string>
  </message>
  <message module="filmprofile_page2">
    <id>Media Info</id>
    <string>Medien Info</string>
  </message>
  <message module="filmprofile_page2">
    <id>Description Side A</id>
    <string>Beschreibung Seite A</string>
  </message>
  <message module="filmprofile_page2">
    <id>Label Side A</id>
    <string>Label Seite A</string>
  </message>
  <message module="filmprofile_page2">
    <id>Duallayer Side A</id>
    <string>Duallayer Seite A</string>
  </message>
  <message module="filmprofile_page2">
    <id>DiscID Side A</id>
    <string>Disk-ID Seite A</string>
  </message>
  <message module="filmprofile_page2">
    <id>Description Side B</id>
    <string>Beschreibung Seite B</string>
  </message>
  <message module="filmprofile_page2">
    <id>Label Side B</id>
    <string>Label Seite B</string>
  </message>
  <message module="filmprofile_page2">
    <id>DiscID Side B</id>
    <string>Disk-ID Seite B</string>
  </message>
  <message module="filmprofile_page2">
    <id>Duallayer Side B</id>
    <string>Duallayer Seite B</string>
  </message>
  <message module="filmprofile_page2">
    <id>Dualsided</id>
    <string>Zweiseitig</string>
  </message>
  <message module="filmprofile_page2">
    <id>Dual Layered</id>
    <string>Zweischichtig</string>
  </message>
  <message module="filmprofile_page2">
    <id>Single Layered</id>
    <string>Einschichtig</string>
  </message>
  <message module="filmprofile_page2">
    <id>Location</id>
    <string>Ort</string>
  </message>
  <message module="filmprofile_page2">
    <id>Slot</id>
    <string>Slot</string>
  </message>
  <message module="filmprofile_page2">
    <id>Various Information</id>
    <string>Verschiedene Informationen</string>
  </message>
  <message module="filmprofile_page2">
    <id>Easter Egg</id>
    <string>Versteckte Features</string>
  </message>
  <message module="filmprofile_page2">
    <id>Awards</id>
    <string>Filmpreise</string>
  </message>
  <message module="filmprofile_page2">
    <id>Winner</id>
    <string>Gewinner</string>
  </message>
  <message module="filmprofile_page2">
    <id>Nominee for</id>
    <string>Nominiert f&uuml;r</string>
  </message>

  <message module="filmprofile_page3">
    <id>Cast</id>
    <string>Darsteller</string>
  </message>
  <message module="filmprofile_page3">
    <id>uncredited</id>
    <string>Nicht aufgef&uuml;hrt</string>
  </message>
  <message module="filmprofile_page3">
    <id>voice</id>
    <string>Stimme</string>
  </message>
  <message module="filmprofile_page3">
    <id>credited as</id>
    <string>aufgef&uuml;hrt als</string>
  </message>
  <message module="filmprofile_page3">
    <id>Crew</id>
    <string>Crew</string>
  </message>

  <message module="filmprofile_page4">
    <id>Date</id>
    <string>Datum</string>
  </message>
  <message module="filmprofile_page4">
    <id>Event</id>
    <string>Ereignis</string>
  </message>
  <message module="filmprofile_page4">
    <id>Phone</id>
    <string>Telefon</string>
  </message>
  <message module="filmprofile_page4">
    <id>Borrowed</id>
    <string>Ausgeliehen</string>
  </message>
  <message module="filmprofile_page4">
    <id>Returned</id>
    <string>Zur&uuml;ck</string>
  </message>
  <message module="filmprofile_page4">
    <id>Note</id>
    <string>Notiz</string>
  </message>

  <message module="filmprofile_status">
    <id>Owned</id>
    <string>Besitz</string>
  </message>
  <message module="filmprofile_status">
    <id>Ordered</id>
    <string>Bestellt</string>
  </message>
  <message module="filmprofile_status">
    <id>WishList</id>
    <string>Wunschliste</string>
  </message>

  <message module="filmprofile_wishpriority">
    <id>Vague Interest</id>
    <string>Vages Interesse</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Like to Have It</id>
    <string>Sch&ouml;n zu haben</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Want It</id>
    <string>Will ich</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Really Want</id>
    <string>Will ich wirklich</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Need It</id>
    <string>Brauche ich</string>
  </message>
  <message module="filmprofile_wishpriority">
    <id>Watched</id>
    <string>Gesehen</string>
  </message>

  <message module="statistics">
    <id>Statistics</id>
    <string>Statistiken</string>
  </message>
  <message module="statistics">
    <id>Other Statistics</id>
    <string>Andere Statistiken</string>
  </message>
  <message module="statistics">
    <id>Director Statistic</id>
    <string>Regisseurstatistik</string>
  </message>
  <message module="statistics">
    <id>Producer Statistic</id>
    <string>Produzentstatistik</string>
  </message>
  <message module="statistics">
    <id>Writer &amp; Screenwriter Statistic</id>
    <string>Autor &amp; Drehbuchautor Statistik</string>
  </message>
  <message module="statistics">
    <id>Composer Statistic</id>
    <string>Komponisten Statistik</string>
  </message>
  <message module="statistics">
    <id>Actor Statistic</id>
    <string>Darstellerstatistik</string>
  </message>
  <message module="statistics">
    <id>What's been watched</id>
    <string>Was wurde gesehen</string>
  </message>
  <message module="statistics">
    <id>Number of DVDs</id>
    <string>Anzahl DVDs</string>
  </message>
  <message module="statistics">
    <id>With Pricing Information</id>
    <string>DVDs mit Preisangabe</string>
  </message>
  <message module="statistics">
    <id>DVDs without a Child Profile</id>
    <string>DVDs ohne ein Kind Profil</string>
  </message>
  <message module="statistics">
    <id>Boxset Profiles</id>
    <string>Boxset Profile</string>
  </message>
  <message module="statistics">
    <id>Child Profiles</id>
    <string>Kind Profile</string>
  </message>
  <message module="statistics">
    <id>DVDs with Collection Number</id>
    <string>DVDs mit Sammlungsnummer</string>
  </message>
  <message module="statistics">
    <id>DVDs with Rating Information</id>
    <string>DVDs mit Angaben zur Altersfreigabe</string>
  </message>
  <message module="statistics">
    <id>Price of all DVDs</id>
    <string>Gesamtpreis</string>
  </message>
  <message module="statistics">
    <id>Average price</id>
    <string>Durchschnittspreis</string>
  </message>
  <message module="statistics">
    <id>Most expensive DVDs</id>
    <string>Die teuersten DVDs</string>
  </message>
  <message module="statistics">
    <id>Cheapest DVDs</id>
    <string>Die g&uuml;nstigsten DVDs</string>
  </message>
  <message module="statistics">
    <id>Length of all DVDs</id>
    <string>Gesamtl&auml;nge</string>
  </message>
  <message module="statistics">
    <id>DVDs with Length Information</id>
    <string>DVDs mit L&auml;ngenangabe</string>
  </message>
  <message module="statistics">
    <id>Hours: about</id>
    <string>Stunden: ca.</string>
  </message>
  <message module="statistics">
    <id>hours</id>
    <string>Stunden</string>
  </message>
  <message module="statistics">
    <id>Days: about</id>
    <string>Tage: ca.</string>
  </message>
  <message module="statistics">
    <id>days</id>
    <string>Tage</string>
  </message>
  <message module="statistics">
    <id>Weeks: about</id>
    <string>Wochen: ca.</string>
  </message>
  <message module="statistics">
    <id>weeks</id>
    <string>Wochen</string>
  </message>
  <message module="statistics">
    <id>Months: about</id>
    <string>Monate: ca.</string>
  </message>
  <message module="statistics">
    <id>months</id>
    <string>Monate</string>
  </message>
  <message module="statistics">
    <id>Years: about</id>
    <string>Jahre: ca.</string>
  </message>
  <message module="statistics">
    <id>years</id>
    <string>Jahre</string>
  </message>
  <message module="statistik">
    <id>Average Length</id>
    <string>Durchschnittsl&auml;nge</string>
  </message>
  <message module="statistics">
    <id>Longest DVDs</id>
    <string>Die l&auml;ngsten DVDs</string>
  </message>
  <message module="statistics">
    <id>Shortest DVDs</id>
    <string>Die k&uuml;rstesten DVDs</string>
  </message>
  <message module="statistics">
    <id>Regioncode</id>
    <string>Regionalcode</string>
  </message>
  <message module="statistics">
    <id>Localities of DVDs</id>
    <string>Herkunftsl&auml;nder der DVDs</string>
  </message>
  <message module="statistics">
    <id>Localities</id>
    <string>Herkunftsl&auml;nder</string>
  </message>
  <message module="statistics">
    <id>Origins of Movies</id>
    <string>Produktionsl&auml;nder der Filme</string>
  </message>
  <message module="statistics">
    <id>Origins</id>
    <string>Produktionsl&auml;nder</string>
  </message>
  <message module="statistics">
    <id>Ratings</id>
    <string>Altersfreigaben</string>
  </message>
  <message module="statistics">
    <id>DVDs</id>
    <string>DVDs</string>
  </message>
  <message module="statistics">
    <id>Year of Purchase</id>
    <string>Kaufjahr</string>
  </message>
  <message module="statistics">
    <id>Detailed Statistic</id>
    <string>Detailierte Statistik</string>
  </message>
  <message module="statistics">
    <id>Production Decade</id>
    <string>Produktionsdekade</string>
  </message>
  <message module="statistics">
    <id>Place of Purchase (Top 10)</id>
    <string>Kaufort (Top 10)</string>
  </message>
  <message module="statistics">
    <id>Place of Purchase</id>
    <string>Kaufort</string>
  </message>
  <message module="statistics">
    <id>Genre (Top 10)</id>
    <string>Genre (Top 10)</string>